Dev adv spa branch
aletrailo/rs2-project pull request #34
Opened 2023-08-21 22:38 UTC by kleutMilica

2023-08-23 17:08 UTC, DarkoMicanovic commented on CoWorkSpace/Spaces.Persistance/Extensions/CreationInfoExtensions.cs
Cela ova klasa je suvisna. Na mestu gde Insetr-ujes, tu pakujes na ovaj nacin.

2023-08-23 17:09 UTC, DarkoMicanovic commented on CoWorkSpace/Spaces.Persistance/Repositories/SpaceRepository.cs
> +            var spaceEntity = creationinfo.ToSpaceEntity();
Ovde stavis SpaceEntity spaceEntity = new new SpaceEntity
            {
                Id = MongoDB.Bson.ObjectId.GenerateNewId().ToString(),
                Name = creationInfo.Name,
                Address = creationInfo.Address,
                Description = creationInfo.Description,
                Image = creationInfo.Image
            };
}

2023-08-23 17:10 UTC, DarkoMicanovic commented on CoWorkSpace/Spaces.Persistance/Spaces.Persistance.csproj
> +    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="7.0.0" />
Pitanje samo: Zbog cega nam ovo treba?

2023-08-23 17:12 UTC, DarkoMicanovic commented on CoWorkSpace/Spaces.Persistance/Repositories/SpaceRepository.cs
> +        public async Task<bool> UpdateSpace(CreationInfo creationinfo)
UpdateAsync mora da primi ceo Space model. Tj ulazni parametri su Space space.

Za razliku od kreiranja, kada se poziva update, pozva se spolja kada Api ima ceo model

2023-08-23 17:36 UTC, DarkoMicanovic requested changes
Generalno prodji sve metode koje su async, trebaju da imaju u nazivu na kraju Async.
Isto, prodji gde god ima naziv promenljive u parametrima da prati full naziv klase (npr: CreationInfoDto creationInfoDto,...)

2023-08-23 17:36 UTC, DarkoMicanovic commented on CoWorkSpace/Spaces.Persistance/Extensions/SpaceExtensions.cs
> +
Ovde ti treba ToEnitity ekstender nad Space.

Pozivaces ga kada radis Update

2023-08-23 17:36 UTC, DarkoMicanovic commented on CoWorkSpace/Spaces.Persistance/Context/SpaceContext.cs
> +            this.settings.ConnectionString = "mongodb://spacesdb:27017"; //kada se pokrece van dokera zakomentarisi ovu liniju
Ovo nisam primetio. Ne znam sto stoji tu. Neka ga sad, uklonice se posle

2023-08-23 17:36 UTC, DarkoMicanovic commented on CoWorkSpace/Spaces.Common/Interfaces/ISpaceRepository.cs
> +        Task InsertSpace(CreationInfo creationinfo);
Metode trebaju da se zovu InsertAsync i UpdateAsync.

Cak mi je bolje AddAsync umesto InsertAsync. Insert (add) treba da ima CreationInfo od parametar, dok Update Spaces

2023-08-23 17:36 UTC, DarkoMicanovic commented on CoWorkSpace/Spaces.Common/Services/SpaceService.cs
> +        public Task InsertAsync(CreationInfo creationInfo)
Nazive i parametre u skladu sa komentarima sa ISpaceRepository

2023-08-23 17:36 UTC, DarkoMicanovic commented on CoWorkSpace/Spaces.Api/Extensions/CreationInfoExtensions.cs
> +        internal static CreationInfo ToCreationInfo(this CreationInfoDto Dto)
Ova metoda treba da se zove ToModel

2023-08-23 17:36 UTC, DarkoMicanovic commented on CoWorkSpace/Spaces.Grpc/Extensions/SpacesResponseExtensions.cs
> +        internal static CreationInfo ToCreationInfo(this SpaceInfo space)
Ova metoda treba da stoji u CreationInfoExtensions fajlu i klasi. Treba da se zove ToModel

2023-08-23 17:36 UTC, DarkoMicanovic commented on CoWorkSpace/Spaces.Grpc/Services/SpaceGrpcService.cs
> +                Console.WriteLine($"Greška prilikom ubacivanja prostora: {ex.Message}");
Ukloni ovo.  Kasnije cemo dodati logove

2023-08-23 17:36 UTC, DarkoMicanovic commented on CoWorkSpace/Spaces.Grpc/Services/SpaceGrpcService.cs
> +                Console.WriteLine($"Greška prilikom ubacivanja prostora: {ex.Message}");
Mislim na Console.WriteLine

2023-08-23 17:36 UTC, DarkoMicanovic commented on CoWorkSpace/Spaces.Api/Controllers/SpacesController.cs
> +            var creationInfo = Dto.ToCreationInfo();
kad preimenujes, ovde ocekujem da pise dto.ToModel()

2023-08-23 17:36 UTC, DarkoMicanovic commented on CoWorkSpace/Spaces.Api/Controllers/SpacesController.cs
> +        public async Task InsertAsync(CreationInfoDto Dto)
Pun naziv. dakle creationInfoDto umesto Dto

2023-08-23 17:36 UTC, DarkoMicanovic commented on CoWorkSpace/Spaces.Api/Controllers/SpacesController.cs
> +        public async Task InsertAsync(CreationInfoDto Dto)
Isto i za UpdateAsync

2023-08-23 17:36 UTC, DarkoMicanovic commented on CoWorkSpace/Advertising.Common/Interfaces/IAdvertisingService.cs
> +        Task<bool> AddAsync(AdSpace adSpace);
Ako je ovo metoda za umetanje novog oglasa, isto treba da ima creationInfo neki iz ove klase. Posle kada pozivas drugi mikroservis napkujes podatke koje on treba da primi

2023-08-23 17:36 UTC, DarkoMicanovic commented on CoWorkSpace/Advertising.Common/Models/AdSpace.cs
Ipak neka ovog imena. Ne mogu sad da smislim neki bolji. :)

2023-08-23 17:36 UTC, DarkoMicanovic commented on CoWorkSpace/Advertising.Common/Models/AdSpace.cs
Mozda AdSpaceInfo ... Kako god ti se vise svidi

2023-08-23 17:36 UTC, DarkoMicanovic commented on CoWorkSpace/Advertising.Api/Services/AdvertisingServices.cs
>  namespace Advertising.Api.Services
Ovde sam ja napravio zajeb.. Nazvao sam klasu AdvertisingSpaces umesto AdvertisingSpace... Ispravicu nekom prilikom

2023-08-23 17:36 UTC, DarkoMicanovic commented on CoWorkSpace/Advertising.Api/Extensions/AdExtension.cs
> +        internal static AdSpace ToAd(this AdInfoDto adInfoDto)
Licno vise volim (a i bolja je praksa) da se nazivaju ove metode ToModel ili ToDto ili ToEntity. sve zavisi sta je povratna vrednost. Ovde bih konkretno nazvao ToModel

2023-08-23 17:36 UTC, DarkoMicanovic commented on CoWorkSpace/Advertising.Api/Controllers/AdvertisingController.cs
> +        public async Task<IActionResult> AddAnAdAsync(AdInfoDto adDto)
Isto, rename-uj da se parametar zove adInfodto. Tj pun naziv kao i klasa

2023-08-23 19:37 UTC, kleutMilica commented on CoWorkSpace/Spaces.Persistance/Repositories/SpaceRepository.cs
> +            var spaceEntity = creationinfo.ToSpaceEntity();
Da proverim da li sam dobro skapirala, li ovako treba da izgleda insert:
public async Task InsertSpace(CreationInfo creationInfo)
{
    SpaceEntity spaceEntity =  new SpaceEntity
        {
            Id = MongoDB.Bson.ObjectId.GenerateNewId().ToString(),
            Name = creationInfo.Name,
            Address = creationInfo.Address,
            Description = creationInfo.Description,
            Image = creationInfo.Image
        };


    await context.GetCollection().InsertOneAsync(spaceEntity);
}

2023-08-23 19:38 UTC, kleutMilica commented on CoWorkSpace/Spaces.Persistance/Spaces.Persistance.csproj
> +    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="7.0.0" />
Ovo je sam negde povukao, ne znam tacno kada i zasto, da ga izbrisem rucno?

2023-08-24 17:14 UTC, DarkoMicanovic approved these changes

2023-08-24 17:14 UTC, DarkoMicanovic commented on CoWorkSpace/Spaces.Grpc/Services/SpaceGrpcService.cs
> +using CreationInfoModel = Spaces.Common.Models.CreationInfo;
Sad videh da si pravila ove aliase. Zar nije moglo samo da importujes Spaces.Common.Models?

2023-08-24 17:14 UTC, DarkoMicanovic commented on CoWorkSpace/Spaces.Common/Services/SpaceService.cs
> +            return this.repository.UpdateSpaceAsync(creationInfo);
Da li si sigurna da ovo radi? Ovaj servis treba da primi space i da ga prosledi repo-u. Sa druge strane, vidim da repo prima Space a ti mu prosledjujes CreationInfo. Proveri to

2023-08-25 12:52 UTC, merged